// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using JsonCSharpClassGenerator;

namespace NovaPoshta
{

    public class Warning
    {
        public Warning(JObject obj)
        {
        }

    }

}
