// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NovaPoshta.NovaPoshtaTrackingJsonTypes;

namespace NovaPoshta.NovaPoshtaTrackingJsonTypes
{

    internal class Datum
    {

        [JsonProperty("Number")]
        public string Number { get; set; }

        [JsonProperty("Status")]
        public string Status { get; set; }

        [JsonProperty("StatusCode")]
        public string StatusCode { get; set; }

        [JsonProperty("RefEW")]
        public string RefEW { get; set; }

        [JsonProperty("BackwardDeliverySubTypesServices")]
        public object[] BackwardDeliverySubTypesServices { get; set; }

        [JsonProperty("BackwardDeliverySubTypesActions")]
        public object[] BackwardDeliverySubTypesActions { get; set; }

        [JsonProperty("UndeliveryReasons")]
        public string UndeliveryReasons { get; set; }

        [JsonProperty("RecipientFullName")]
        public string RecipientFullName { get; set; }

        [JsonProperty("CargoDescriptionString")]
        public string CargoDescriptionString { get; set; }

        [JsonProperty("RedeliverySum")]
        public string RedeliverySum { get; set; }

        [JsonProperty("RedeliveryPayer")]
        public string RedeliveryPayer { get; set; }

        [JsonProperty("AfterpaymentOnGoodsCost")]
        public string AfterpaymentOnGoodsCost { get; set; }

        [JsonProperty("LastCreatedOnTheBasisPayerType")]
        public string LastCreatedOnTheBasisPayerType { get; set; }

        [JsonProperty("LastTransactionDateTimeGM")]
        public string LastTransactionDateTimeGM { get; set; }

        [JsonProperty("CounterpartySenderDescription")]
        public string CounterpartySenderDescription { get; set; }

        [JsonProperty("CounterpartyRecipientDescription")]
        public string CounterpartyRecipientDescription { get; set; }

        [JsonProperty("SenderAddress")]
        public string SenderAddress { get; set; }

        [JsonProperty("RecipientAddress")]
        public string RecipientAddress { get; set; }

        [JsonProperty("ClientBarcode")]
        public string ClientBarcode { get; set; }
    }

}
