// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NovaPoshta.NovaPoshtaTrackingJsonTypes;

namespace NovaPoshta.NovaPoshtaTrackingJsonTypes
{

    internal class Warning
    {

        [JsonProperty("ID_{num}")]
        public string IDNum { get; set; }
    }

}
